// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading;
using Foundation;
using UIKit;

namespace test_app_kitchen_timer
{
	public partial class MyViewController : UIViewController
	{
        private Timer _timer;
        private TimeSpan _remainingTime = new TimeSpan(0);
        private bool _isStart = false;

		public MyViewController (IntPtr handle) : base (handle)
		{
		}

        // 初回読み込み
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            StartButton.TouchUpInside += StartButton_TouchUpInside;
            Add10MinButton.TouchUpInside += Add10MinButton_TouchUpInside;
            Add1MinButton.TouchUpInside += (s, e) =>
            {
                _remainingTime = _remainingTime.Add(TimeSpan.FromMinutes(1));
                ShowRemainingTime();
            };
            Add10SecButton.TouchUpInside += (s, e) =>
            {
                _remainingTime = _remainingTime.Add(TimeSpan.FromSeconds(10));
                ShowRemainingTime();
            };
            Add1SecButton.TouchUpInside += (s, e) =>
            {
                _remainingTime = _remainingTime.Add(TimeSpan.FromSeconds(1));
                ShowRemainingTime();
            };

            // タイマーの初期設定
            _timer = new Timer(Timer_OnTick, null, 0, 100);

            SetButtonBorder(StartButton);
            SetButtonBorder(Add10MinButton);
            SetButtonBorder(Add1MinButton);
            SetButtonBorder(Add10SecButton);
            SetButtonBorder(Add1SecButton);
            SetButtonBorder(ClearButton);
        }

        private void Add10MinButton_TouchUpInside(object sender, EventArgs e)
        {
            _remainingTime = _remainingTime.Add(TimeSpan.FromMinutes(10));
            ShowRemainingTime();
        }

        // スタートボタンの表示切り替え
        private void StartButton_TouchUpInside(object sender, EventArgs e)
        {
            _isStart = !_isStart;
            if (_isStart)
            {
                StartButton.SetTitle("ストップ", UIControlState.Normal);
            }
            else
            {
                StartButton.SetTitle("スタート", UIControlState.Normal);
            }
        }

        // タイマーのテキスト更新
        private void ShowRemainingTime()
        {
            RemainingTimeLabel.Text = string.Format("{0:f0}:{1:d2}",
                _remainingTime.TotalMinutes,
                _remainingTime.Seconds
                );
        }

        // タイマーのカウントダウン部分
        private void Timer_OnTick(object state)
        {
            if (!_isStart)
            {
                return;
            }

            InvokeOnMainThread(() =>
            {
                _remainingTime = _remainingTime.Add(TimeSpan.FromMilliseconds(-100));
                if(_remainingTime.TotalSeconds <= 0)
                {
                    _isStart = false;
                    _remainingTime = new TimeSpan(0);
                    StartButton.SetTitle("スタート", UIControlState.Normal);

                    // アラームを鳴らす
                    var sound = new AudioToolbox.SystemSound(1005);
                    sound.PlayAlertSound();
                }

                ShowRemainingTime();
            });
        }

        // ボタンのデザイン調整
        private void SetButtonBorder(UIButton button)
        {
            button.Layer.CornerRadius = 3;
            button.Layer.BorderColor = UIColor.LightGray.CGColor;
            button.Layer.BorderWidth = 1f;
        }
    }
}
